services:
  # ==========================================
  # 1. Backend Core (Producer)
  # ==========================================
  backend-app:
    build:
      context: .
      dockerfile: prioritas/Dockerfile
    container_name: prioritas-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-db:5432/prioritas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      backend-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - prioritas-net

  # ==========================================
  # 2. Notification Service (Consumer)
  # ==========================================
  notification-app:
    build:
      context: .
      dockerfile: notification-app/Dockerfile
    container_name: prioritas-notification
    environment:
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - EMAIL_FROM=gabrielalcantarars@gmail.com
      - EMAIL_PASS=vammgunalujgxiql
      - EMAIL_TARGET_LIST=gabrielalcantarars@gmail.com
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prioritas-net

  # ==========================================
  # 3. Database
  # ==========================================
  backend-db:
    image: postgres:18-alpine
    container_name: prioritas-db
    environment:
      - POSTGRES_DB=prioritas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prioritas-net

  # ==========================================
  # 4. RabbitMQ (Broker + UI)
  # ==========================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: prioritas-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - prioritas-net

networks:
  prioritas-net:
    driver: bridge